"use client"
/* todo - move provider to providers.ts and remove 'use client' */

import './globals.css'
import { MantineProvider } from '@mantine/core';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <MantineProvider withGlobalStyles withNormalizeCSS>
        <body>{children}</body>
      </MantineProvider>
    </html>
  )
}
