import React, {ReactNode} from "react";
import './globals.css'
import {Providers} from './providers'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout( {children,}: {children: ReactNode}) {
	return (
		<html lang="en">
            <body>
                <Providers session={null}>
                    {children}
                </Providers>
            </body>
		</html>
	)
}
